{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.8.16","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"\n!pip install --upgrade pip\n!pip install python-gdcm\n\n# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using \"Save & Run All\" \n# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2023-01-10T05:53:48.317231Z","iopub.execute_input":"2023-01-10T05:53:48.317490Z","iopub.status.idle":"2023-01-10T05:53:59.307865Z","shell.execute_reply.started":"2023-01-10T05:53:48.317461Z","shell.execute_reply":"2023-01-10T05:53:59.306666Z"},"trusted":true},"execution_count":1,"outputs":[{"name":"stdout","text":"Requirement already satisfied: pip in /usr/local/lib/python3.8/site-packages (22.0.4)\nCollecting pip\n  Downloading pip-22.3.1-py3-none-any.whl (2.1 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.1/2.1 MB\u001b[0m \u001b[31m18.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n\u001b[?25hInstalling collected packages: pip\n  Attempting uninstall: pip\n    Found existing installation: pip 22.0.4\n    Uninstalling pip-22.0.4:\n      Successfully uninstalled pip-22.0.4\nSuccessfully installed pip-22.3.1\n\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n\u001b[0mCollecting python-gdcm\n  Downloading python_gdcm-3.0.20-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m13.0/13.0 MB\u001b[0m \u001b[31m71.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n\u001b[?25hInstalling collected packages: python-gdcm\nSuccessfully installed python-gdcm-3.0.20\n\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n\u001b[0m","output_type":"stream"}]},{"cell_type":"code","source":"!pip install -qU python-gdcm pydicom pylibjpeg\n\n!pip install scikit-image","metadata":{"execution":{"iopub.status.busy":"2023-01-10T05:57:58.420003Z","iopub.execute_input":"2023-01-10T05:57:58.420743Z","iopub.status.idle":"2023-01-10T05:58:10.266829Z","shell.execute_reply.started":"2023-01-10T05:57:58.420707Z","shell.execute_reply":"2023-01-10T05:58:10.265789Z"},"trusted":true},"execution_count":6,"outputs":[{"name":"stdout","text":"\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n\u001b[0mCollecting scikit-image\n  Downloading scikit_image-0.19.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.0 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m14.0/14.0 MB\u001b[0m \u001b[31m72.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n\u001b[?25hRequirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.8/site-packages (from scikit-image) (1.24.1)\nRequirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/site-packages (from scikit-image) (22.0)\nCollecting PyWavelets>=1.1.1\n  Downloading PyWavelets-1.4.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.9 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.9/6.9 MB\u001b[0m \u001b[31m82.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m:00:01\u001b[0m00:01\u001b[0m\n\u001b[?25hCollecting tifffile>=2019.7.26\n  Downloading tifffile-2022.10.10-py3-none-any.whl (210 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m210.3/210.3 kB\u001b[0m \u001b[31m22.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hCollecting imageio>=2.4.1\n  Downloading imageio-2.24.0-py3-none-any.whl (3.4 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m3.4/3.4 MB\u001b[0m \u001b[31m82.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m:00:01\u001b[0m\n\u001b[?25hRequirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.8/site-packages (from scikit-image) (1.10.0)\nCollecting networkx>=2.2\n  Downloading networkx-3.0-py3-none-any.whl (2.0 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.0/2.0 MB\u001b[0m \u001b[31m74.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hRequirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in /usr/local/lib/python3.8/site-packages (from scikit-image) (9.4.0)\nInstalling collected packages: tifffile, PyWavelets, networkx, imageio, scikit-image\nSuccessfully installed PyWavelets-1.4.1 imageio-2.24.0 networkx-3.0 scikit-image-0.19.3 tifffile-2022.10.10\n\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n\u001b[0m","output_type":"stream"}]},{"cell_type":"code","source":"from functools import partial\nimport multiprocessing as mp\nfrom pathlib import Path\nimport numpy as np\nimport pandas as pd\nimport pydicom\nfrom skimage.transform import resize","metadata":{"execution":{"iopub.status.busy":"2023-01-10T05:58:16.606002Z","iopub.execute_input":"2023-01-10T05:58:16.606995Z","iopub.status.idle":"2023-01-10T05:58:18.012818Z","shell.execute_reply.started":"2023-01-10T05:58:16.606953Z","shell.execute_reply":"2023-01-10T05:58:18.011881Z"},"trusted":true},"execution_count":7,"outputs":[]},{"cell_type":"code","source":"# RESCALE_TO = (512, 512)\nRESCALE_TO = (256, 256)\nDATA_PATH = Path(\"/kaggle/input/rsna-breast-cancer-detection\")\nTRAINING_IMAGES = DATA_PATH.joinpath(\"train_images\").iterdir()\nTRAINING_DATA = DATA_PATH.joinpath(\"train.csv\")\nTEST_IMAGES = DATA_PATH.joinpath(\"test_images\").iterdir()\nTEST_DATA = DATA_PATH.joinpath(\"test.csv\")","metadata":{"execution":{"iopub.status.busy":"2023-01-10T05:58:37.191447Z","iopub.execute_input":"2023-01-10T05:58:37.192392Z","iopub.status.idle":"2023-01-10T05:58:37.197529Z","shell.execute_reply.started":"2023-01-10T05:58:37.192358Z","shell.execute_reply":"2023-01-10T05:58:37.196729Z"},"trusted":true},"execution_count":8,"outputs":[]},{"cell_type":"code","source":"def dicom_file_to_data(path):\n    dicom = pydicom.read_file(path)\n    data = dicom.pixel_array\n    if dicom.PhotometricInterpretation == \"MONOCHROME1\":\n        data = np.amax(data) - data\n    return data * dicom.RescaleSlope + dicom.RescaleIntercept","metadata":{"execution":{"iopub.status.busy":"2023-01-10T05:59:09.425799Z","iopub.execute_input":"2023-01-10T05:59:09.426741Z","iopub.status.idle":"2023-01-10T05:59:09.431777Z","shell.execute_reply.started":"2023-01-10T05:59:09.426688Z","shell.execute_reply":"2023-01-10T05:59:09.430936Z"},"trusted":true},"execution_count":9,"outputs":[]},{"cell_type":"code","source":"TR_IMAGES = []\nTR_DATA = []\ndef process_training_image_directory(directory_path, training_data=None):\n    print(f\"processing image directory: {directory_path}\")\n    for image_path in directory_path.iterdir():\n        print(f\"\\tTraining image: {image_path}\")\n        image_data = dicom_file_to_data(image_path)\n        patient_id = image_path.parent.name\n        image_id = image_path.stem\n        resized_image = resize(image_data, (RESCALE_TO))\n        df = training_data[(training_data.patient_id == int(patient_id)) & (training_data.image_id == int(image_id))]\n        TR_IMAGES.append(resized_image)\n        TR_DATA.append(df['cancer'].iloc[0])\n    return TR_IMAGES, TR_DATA","metadata":{"execution":{"iopub.status.busy":"2023-01-10T05:59:20.815546Z","iopub.execute_input":"2023-01-10T05:59:20.816377Z","iopub.status.idle":"2023-01-10T05:59:20.824300Z","shell.execute_reply.started":"2023-01-10T05:59:20.816341Z","shell.execute_reply":"2023-01-10T05:59:20.823280Z"},"trusted":true},"execution_count":10,"outputs":[]},{"cell_type":"code","source":"training_data_df = pd.read_csv(TRAINING_DATA)\nTRAINING_IMAGES = DATA_PATH.joinpath(\"train_images\", \"10130\")\nimages, data = process_training_image_directory(TRAINING_IMAGES, training_data_df)","metadata":{"execution":{"iopub.status.busy":"2023-01-10T05:59:35.832945Z","iopub.execute_input":"2023-01-10T05:59:35.833373Z","iopub.status.idle":"2023-01-10T05:59:47.720065Z","shell.execute_reply.started":"2023-01-10T05:59:35.833342Z","shell.execute_reply":"2023-01-10T05:59:47.718476Z"},"trusted":true},"execution_count":11,"outputs":[{"name":"stdout","text":"processing image directory: /kaggle/input/rsna-breast-cancer-detection/train_images/10130\n\tTraining image: /kaggle/input/rsna-breast-cancer-detection/train_images/10130/1165309236.dcm\n\tTraining image: /kaggle/input/rsna-breast-cancer-detection/train_images/10130/2110820077.dcm\n\tTraining image: /kaggle/input/rsna-breast-cancer-detection/train_images/10130/388811999.dcm\n\tTraining image: /kaggle/input/rsna-breast-cancer-detection/train_images/10130/1013166704.dcm\n\tTraining image: /kaggle/input/rsna-breast-cancer-detection/train_images/10130/613462606.dcm\n\tTraining image: /kaggle/input/rsna-breast-cancer-detection/train_images/10130/1672636630.dcm\n\tTraining image: /kaggle/input/rsna-breast-cancer-detection/train_images/10130/1360338805.dcm\n","output_type":"stream"}]},{"cell_type":"code","source":"def test_model():\n    testing_data_df = pd.read_csv(TEST_DATA)\n    for image_path in TEST_IMAGES.iterdir():\n        image = dicom_file_to_data(image_path)\n        #TODO: call the model with image","metadata":{"execution":{"iopub.status.busy":"2023-01-10T06:00:03.953234Z","iopub.execute_input":"2023-01-10T06:00:03.954430Z","iopub.status.idle":"2023-01-10T06:00:03.959957Z","shell.execute_reply.started":"2023-01-10T06:00:03.954391Z","shell.execute_reply":"2023-01-10T06:00:03.959020Z"},"trusted":true},"execution_count":12,"outputs":[]},{"cell_type":"code","source":"import os \nos.system('pip install scikit-learn')","metadata":{"execution":{"iopub.status.busy":"2023-01-10T06:03:32.978328Z","iopub.execute_input":"2023-01-10T06:03:32.979564Z","iopub.status.idle":"2023-01-10T06:03:39.070115Z","shell.execute_reply.started":"2023-01-10T06:03:32.979529Z","shell.execute_reply":"2023-01-10T06:03:39.069187Z"},"trusted":true},"execution_count":16,"outputs":[{"name":"stdout","text":"Collecting scikit-learn\n  Downloading scikit_learn-1.2.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.7 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 54.5 MB/s eta 0:00:00\nRequirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/site-packages (from scikit-learn) (1.24.1)\nRequirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.8/site-packages (from scikit-learn) (1.10.0)\nCollecting joblib>=1.1.1\n  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 29.3 MB/s eta 0:00:00\nCollecting threadpoolctl>=2.0.0\n  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)\nInstalling collected packages: threadpoolctl, joblib, scikit-learn\nSuccessfully installed joblib-1.2.0 scikit-learn-1.2.0 threadpoolctl-3.1.0\n","output_type":"stream"},{"name":"stderr","text":"WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n","output_type":"stream"},{"execution_count":16,"output_type":"execute_result","data":{"text/plain":"0"},"metadata":{}}]},{"cell_type":"code","source":"import tensorflow as tf\nfrom keras.models import Sequential\nfrom keras.layers import Dense, Dropout, Flatten\nfrom keras.layers import Conv2D, MaxPooling2D\nfrom keras.preprocessing import image\nfrom sklearn.model_selection import train_test_split\nimport numpy as np\n\nmodel = Sequential()\nmodel.add(Conv2D(8, kernel_size=(3, 3),activation='relu',input_shape=(256,256,1)))\n\nmodel.add(MaxPooling2D(pool_size=(2, 2)))\nmodel.add(Conv2D(64,(3, 3), activation='relu'))\nmodel.add(Dropout(0.25))\nmodel.add(Flatten())\nmodel.add(Dense(100, activation='relu'))\nmodel.add(Dropout(0.5))\nmodel.add(Dense(1, activation='softmax'))\n\nX_train, X_test, y_train, y_test = train_test_split(TR_IMAGES, TR_DATA, random_state=42, test_size=0.2,shuffle=True)\nmodel.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])\nX_train = np.expand_dims(X_train, axis=-1)\nX_test=np.expand_dims(X_train, axis=-1)\nmodel.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))","metadata":{"execution":{"iopub.status.busy":"2023-01-10T06:04:00.743994Z","iopub.execute_input":"2023-01-10T06:04:00.745172Z","iopub.status.idle":"2023-01-10T06:04:01.353172Z","shell.execute_reply.started":"2023-01-10T06:04:00.745134Z","shell.execute_reply":"2023-01-10T06:04:01.351766Z"},"trusted":true},"execution_count":17,"outputs":[{"name":"stderr","text":"2023-01-10 06:04:00.868203: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n2023-01-10 06:04:00.868262: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)\n2023-01-10 06:04:00.868300: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (5a7a7a1502c0): /proc/driver/nvidia/version does not exist\n2023-01-10 06:04:00.868685: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n","output_type":"stream"},{"traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","Cell \u001b[0;32mIn[17], line 24\u001b[0m\n\u001b[1;32m     22\u001b[0m X_train \u001b[38;5;241m=\u001b[39m np\u001b[38;5;241m.\u001b[39mexpand_dims(X_train, axis\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m)\n\u001b[1;32m     23\u001b[0m X_test\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39mexpand_dims(X_train, axis\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m)\n\u001b[0;32m---> 24\u001b[0m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m10\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mvalidation_data\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mX_test\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_test\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n","File \u001b[0;32m/usr/local/lib/python3.8/site-packages/keras/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28mNone\u001b[39m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n","File \u001b[0;32m/usr/local/lib/python3.8/site-packages/keras/engine/data_adapter.py:1081\u001b[0m, in \u001b[0;36mselect_data_adapter\u001b[0;34m(x, y)\u001b[0m\n\u001b[1;32m   1078\u001b[0m adapter_cls \u001b[38;5;241m=\u001b[39m [\u001b[38;5;28mcls\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m \u001b[38;5;28mcls\u001b[39m \u001b[38;5;129;01min\u001b[39;00m ALL_ADAPTER_CLS \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mcls\u001b[39m\u001b[38;5;241m.\u001b[39mcan_handle(x, y)]\n\u001b[1;32m   1079\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m adapter_cls:\n\u001b[1;32m   1080\u001b[0m     \u001b[38;5;66;03m# TODO(scottzhu): This should be a less implementation-specific error.\u001b[39;00m\n\u001b[0;32m-> 1081\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[1;32m   1082\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mFailed to find data adapter that can handle input: \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m, \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(\n\u001b[1;32m   1083\u001b[0m             _type_name(x), _type_name(y)\n\u001b[1;32m   1084\u001b[0m         )\n\u001b[1;32m   1085\u001b[0m     )\n\u001b[1;32m   1086\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(adapter_cls) \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m1\u001b[39m:\n\u001b[1;32m   1087\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\n\u001b[1;32m   1088\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mData adapters should be mutually exclusive for \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1089\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhandling inputs. Found multiple adapters \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m to handle \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1090\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124minput: \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m, \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(adapter_cls, _type_name(x), _type_name(y))\n\u001b[1;32m   1091\u001b[0m     )\n","\u001b[0;31mValueError\u001b[0m: Failed to find data adapter that can handle input: <class 'numpy.ndarray'>, (<class 'list'> containing values of types {\"<class 'numpy.int64'>\"})"],"ename":"ValueError","evalue":"Failed to find data adapter that can handle input: <class 'numpy.ndarray'>, (<class 'list'> containing values of types {\"<class 'numpy.int64'>\"})","output_type":"error"}]},{"cell_type":"code","source":"","metadata":{},"execution_count":null,"outputs":[]}]}